name: wokwi_test
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:
  wokwi_test:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Checkout tt tools repo
      uses: actions/checkout@v3
      with:
        repository: tinytapeout/tt-support-tools
        path: tt
        ref: tt07

    # need python and requirements
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python --version
        python -m pip install -r test/requirements.txt
        python -m pip install -r tt/requirements.txt

    - name: Install iverlog
      run: |
        sudo apt-get install -y iverilog

    # fetch the truth table
    - name: Fetch Verilog and Build Config
      run: ./tt/tt_tool.py --create-user-config

    # does the wokwi project have a truthtable?
    - name: Check the Truthtable Exists
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "src/truthtable.md"

    - name: Test
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        cd src
        unset PYTHONHOME
        echo "PYTHONPATH: $PYTHONPATH"
        make clean
        make
        # make will return success even if the test fails, so check for failure in the results.xml
        ! grep failure results.xml

    - name: Upload VCD
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
          name: test-vcd
          path: src/*.vcd
